version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    restart: on-failure
    networks:
      - isi
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - isi
  service-account:
    build:
      context: ./service-account
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8787:8787"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - isi
  service-journal:
    build:
      context: ./service-journal
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8585:8585"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - isi
volumes:
  postgres-data:
networks:
  isi:
    external: true
